#!/bin/sh
npm install -g grunt-cli
npm install
grunt init
grunt prod
npm install sqlite3 --save 

ip=$(hostname -i)

sed -i "s/^[ \t]*host.*/    host: \'$ip\',/" /var/lib/megam/gulp/Ghos/config.js
sed -i "s/^[ \t]*url.*/    url: \'http:\/\/$ip:2368\',/" /var/lib/megam/gulp/Ghos/config.js
 npm start --production


